sudo: required
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.3.3
addons:
  apt:
    packages:
      - oracle-java8-installer
services:
  - redis-server
before_install:
  - sudo update-java-alternatives -s java-8-oracle
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - java -version
  - sudo rm -rf /var/lib/cassandra/*
  - wget http://www-us.apache.org/dist/cassandra/3.10/apache-cassandra-3.10-bin.tar.gz && tar -xvzf apache-cassandra-3.9-bin.tar.gz
  - sudo sh ./apache-cassandra-3.9/bin/cassandra -R
  - sleep 20
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - bundle install
  - RAILS_ENV=test rake cequel:keyspace:create
  - RAILS_ENV=test rake rails cequel:migrate
script:
  - 'CODECOV_TOKEN=18c1f6b2-e46a-4fe0-86d1-7e634e441410 bundle exec rails t'
