sudo: required
dist: trusty
language: ruby
cache: bundler
rvm:
  - 2.3.3
services:
  - redis-server
  - cassandra
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - RAILS_ENV=test rake cequel:keyspace:create
  - RAILS_ENV=test rake cequel:migrate
script:
  - 'CODECOV_TOKEN=18c1f6b2-e46a-4fe0-86d1-7e634e441410 bundle exec rails t'
